name: WPF App Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag version. (ex. 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will skip release."
        required: true
        default: false
        type: boolean
      prerelease:
        description: "prerelease: true will create a pre-release."
        required: true
        default: false
        type: boolean

env:
  PROJECT_NAME: FAManagementStudio
  APP_PATH: ./FAManagementStudio/FAManagementStudio.csproj
  DOTNET_VERSION: 9.0.x
  BUILD_CONFIGURATION: Release
  OUTPUT_DIR: ./publish
  ZIP_BETA: FAManagementStudio_x64_beta.zip
  ZIP_STABLE: FAManagementStudio_x64_stable.zip

jobs:
  build:
    name: Build and Publish WPF App
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build project
        run: dotnet build ${{ env.APP_PATH }} -c ${{ env.BUILD_CONFIGURATION }} -p:Version=${{ inputs.tag }} -p:Platform=x64

      - name: Run tests
        run: dotnet test --no-build

      - name: Publish project
        run: dotnet publish ${{ env.APP_PATH }} -c ${{ env.BUILD_CONFIGURATION }} -p:Version=${{ inputs.tag }} --self-contained true --runtime win-x64 -p:Platform=x64 -p:DebugSymbols=false --output ${{ env.OUTPUT_DIR }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.OUTPUT_DIR }}

  release:
    name: Create GitHub Release and Upload ZIP
    if: ${{ !inputs.dry-run }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install zip (if missing)
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Download build artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ env.PROJECT_NAME }}
          path: artifact

      - name: Create zip file
        run: |
          cd artifact
          zip -r ../${{ inputs.prerelease && env.ZIP_BETA || env.ZIP_STABLE }} .

      - name: Create GitHub release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          name: ${{ inputs.prerelease && format('{0}-pre-v{1}', env.PROJECT_NAME, inputs.tag) || format('{0}-v{1}', env.PROJECT_NAME, inputs.tag) }}
          tag_name: ${{ inputs.prerelease && format('{0}-pre-v{1}', env.PROJECT_NAME, inputs.tag) || format('{0}-v{1}', env.PROJECT_NAME, inputs.tag) }}
          target_commitish: ${{ github.ref }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
          files: ${{ inputs.prerelease && format('./{0}', env.ZIP_BETA) || format('./{0}', env.ZIP_STABLE) }}
